# Assignment 2


## Q1. Creating and Inspecting NumPy Arrays
Create the following two NumPy arrays:
A = [10, 20, 30, 40, 50]\
B = [
 [1, 2, 3],\
 [4, 5, 6]
]\
Using NumPy, display the following information for both arrays:\
• The array itself.\
• Number of dimensions using ndim.\
• Shape using shape.\
• Total number of elements using size.\
• Data type using dtype.


In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60])
b=np.array([
    [1,2,3],
    [4,5,6]
])


print("array:",a)
print("array:",b)

print("Dimension of a",a.ndim)
print("Dimension of b",b.ndim)


print("shape of a",a.shape)
print("shape of a",b.shape)


print("size of a",a.size)
print("size of b",b.size)

print("datatype of a",a.dtype)
print("datatype of b",a.dtype)

array: [10 20 30 40 50 60]
array: [[1 2 3]
 [4 5 6]]
Dimension of a 1
Dimension of b 2
shape of a (6,)
shape of a (2, 3)
size of a 6
size of b 6
datatype of a int64
datatype of b int64


## Q2. NumPy Array-Creation Functions
Create an array containing 20 elements using each of the following NumPy functions:\
• np.arange()\
• np.linspace()\
• np.zeros()\
• np.ones()\
For each function:\
• Display the resulting array.\
• Specify the shape of the resulting array.\
• Explain what the function does.\
• Give one practical application where the function could be useful.

In [ ]:
a=np.arange(20,40)
print(a)
print("shape of a",a.shape)


b=np.linspace(20,40,num=20)
print(b)
print("shape of b",b.shape)


c=np.zeros(20)
print(c)
print("shape of c",c.shape)


d=np.ones(20)
print(d)
print("shape of d",d.shape)





[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
shape of a (20,)
[20.         21.05263158 22.10526316 23.15789474 24.21052632 25.26315789
 26.31578947 27.36842105 28.42105263 29.47368421 30.52631579 31.57894737
 32.63157895 33.68421053 34.73684211 35.78947368 36.84210526 37.89473684
 38.94736842 40.        ]
shape of b (20,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
shape of c (20,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
shape of d (20,)


np.arange():
Generates an array of sequentially increasing values from a start value up to, but excluding, a stop value.

Application: Creating fixed hour slots to index financial transactions across a standard workday.

np.linspace():
 Generates a specified number of mathematically equidistant values between a precise start and end point.

 Application: Creating a smooth set of sample points to plot physics wave curves cleanly.

np.zeros():
Generates a brand new array of a specified size completely filled with the number zero.

Application: Creating a blank digital canvas to build a machine learning image mask from scratch.

np.ones()
Generates a brand new array of a specified size completely filled with the number one.

Application: Setting up base neural network weights that must begin with a uniform starting value.

##Q3. NumPy Indexing and Slicing  
Create the following matrix: \
A = np.arange(1, 26).reshape(5, 5) \
The resulting matrix will contain values from 1 to 25. Using only NumPy indexing, slicing, and Boolean masking,
perform the following operations: \
• Extract the first row. \
• Extract the last row. \
• Extract the first column. \
• Extract the last column. \
• Extract the middle 3 × 3 matrix. \
• Extract all even numbers. \
• Extract all values greater than 15. \
• Reverse the order of the rows. \
• Reverse the order of the columns.

In [ ]:
a= np.arange(1, 26).reshape(5, 5)
print("array a:",a)
print("first row of array:",a[:1,])
print("last row of array:",a[len(a)-1:,])
print("first column of array:",a[:,:1])
print("last column of array:",a[:,len(a)-1:])
print("middle 3*3 array:",a[len(a)//2-1:len(a)//2+2,len(a)//2-1:len(a)//2+2])
mask = a%2==0
print(mask)
print("all even numbers in array:",a[mask])
mask2=a>15
print("all numbers greater than 15: ",a[mask2])
print("reversed array:",a[::-1])
print("reversed array:",a[:,::-1])


array a: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row of array: [[1 2 3 4 5]]
last row of array: [[21 22 23 24 25]]
first column of array: [[ 1]
 [ 6]
 [11]
 [16]
 [21]]
last column of array: [[ 5]
 [10]
 [15]
 [20]
 [25]]
middle 3*3 array: [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]
all even numbers in array: [ 2  4  6  8 10 12 14 16 18 20 22 24]
all numbers greater than 15:  [16 17 18 19 20 21 22 23 24 25]
reversed array: [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
reversed array: [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


##Q4. NumPy Data Types and Type Conversion  
Create the following NumPy array: \
A = np.array([10, 20, 30, 40, 50]) \
Convert the array sequentially into the following data types: \
• int32 \
• float64 \
• int16 \
For each conversion: \
• Display the array. \
• Display its data type. \
• Explain why data-type conversion may be useful in numerical computing.

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print("original a:",a)
print("type of a:",a.dtype)
a=a.astype("int32")
print("int32 array",a)
print("type of a:",a.dtype)
a=a.astype("float64")
print("float64 array",a)
print("type of a:",a.dtype)

# Data-type conversion is a critical tool in numerical computing because hardware has finite limits. Choosing the correct data type balances computational speed, memory consumption, and mathematical precision.

original a: [10 20 30 40 50]
type of a: int64
int32 array [10 20 30 40 50]
type of a: int32
float64 array [10. 20. 30. 40. 50.]
type of a: float64


##Q5. Array Reshaping  
Create: \
A = np.arange(1, 25) \
Reshape this array into each of the following shapes: \
• 2 × 12 \
• 3 × 8 \
• 4 × 6 \
• 6 × 4 \
For every resulting array: \
• Display the matrix. \
• Display its shape. \
• Display its size.

In [ ]:
a= np.arange(1, 25)
# Reshape this array into each of the following shapes:
# • 2 × 12
# • 3 × 8
# • 4 × 6
# • 6 × 4
# For every resulting array:
# • Display the matrix.
# • Display its shape.
# • Display its size.
b=a.reshape(2,12)
print("2*12 array:\n",b)
print("shape of b:",b.shape)
print("size of b:",b.size)

b=a.reshape(3,8)
print("3*8 array:\n",b)
print("shape of b:",b.shape)
print("size of b:",b.size)

b=a.reshape(4,6)
print("4*6 array:\n",b)
print("shape of b:",b.shape)
print("size of b:",b.size)

b=a.reshape(6,4)
print("6*4 array:\n",b)
print("shape of b:",b.shape)
print("size of b:",b.size)

2*12 array:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
shape of b: (2, 12)
size of b: 24
3*8 array:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
shape of b: (3, 8)
size of b: 24
4*6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape of b: (4, 6)
size of b: 24
6*4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape of b: (6, 4)
size of b: 24


##Q6. Vectorized Student Marks Processing  
Consider the following student marks: \
marks = np.array([
45, 67, 89, 32, \
76, 91, 55, 43 \
The university has decided to provide 5 bonus marks to every student. Using NumPy: \
• Add 5 marks to every student. \
• Ensure that no student's marks exceed 100. \
• Calculate the average marks. \
• Find the highest marks. \
• Find the lowest marks. \
• Find the number of students who scored at least 50 after adding the bonus.

In [ ]:
marks = np.array([ 45, 67, 89, 32,76, 91, 55, 43])
print(np.clip(marks+5, a_min=0, a_max=100))
print("average marks:",np.average(marks))
print("highest marks:",np.max(marks))
print("lowest marks:",np.min(marks))
mask=marks>50
print("marks greater 50",marks[mask])
print("num of student got 50+:",len(marks[mask]))

[50 72 94 37 81 96 60 48]
average marks: 62.25
highest marks: 91
lowest marks: 32
marks greater 50 [67 89 76 91 55]
num of student got 50+: 5


##Q7. Boolean Masking and Conditional Data Modification  
Consider the following temperature dataset: \
temperature = np.array([ \
32, 28, 35, 40, 25, \
30, 42, 27, 38 \
]) \
Using NumPy Boolean masking: \
• Extract all temperatures greater than 35. \
• Extract temperatures between 28 and 38 inclusive. \
• Count how many temperatures are greater than 35. \
• Count how many temperatures are below 30. \
• Replace every temperature greater than 40 with 40. \
• Replace every temperature below 28 with 28. \
• Display the final modified array.

In [5]:
temperature = np.array([32, 28, 35, 40, 25,30, 42, 27, 38])
tempgreat=temperature[temperature>35]
print("temperatures greater than 35:",tempgreat)
tempbetween=temperature[(temperature>=28) & (temperature<=38)]
print("temperatures between 28 and 38:",tempbetween)
print("num of temperatures greater than 35:",len(tempgreat))
print("num of temperatures less than 30:",len(temperature[temperature<30]))
temperature[temperature>40]=40
temperature[temperature<28]=28
print("modified temperature:",temperature)

temperatures greater than 35: [40 42 38]
temperatures between 28 and 38: [32 28 35 30 38]
num of temperatures greater than 35: 3
num of temperatures less than 30: 3
modified temperature: [32 28 35 40 28 30 40 28 38]


Q8. Statistical Analysis Using NumPy  \
Given: \
data = np.array([  
12, 15, 18, 21, \
25, 30, 35, 40 \
])\
Using NumPy, calculate:\
• Mean\
• Median\
• Variance \
• Standard deviation \
• Minimum \
• Maximum \
• Range \
• 25th percentile \
• 50th percentile \
• 75th percentile

In [7]:
data = np.array([
12, 15, 18, 21,
25, 30, 35, 40
])
print("mean:",np.mean(data))
print("median:",np.median(data))
print("variance:",np.var(data))
print("standard deviation:",np.std(data))
print("minimum:",np.min(data))
print("maximum:",np.max(data))
print("range:",np.max(data)-np.min(data))
p25, p50, p75 = np.percentile(data, [25, 50, 75])
print(f"25th Percentile: {p25}")
print(f"50th Percentile (Median): {p50}")
print(f"75th Percentile: {p75}")

mean: 24.5
median: 23.0
variance: 85.25
standard deviation: 9.233092656309694
minimum: 12
maximum: 40
range: 28
25th Percentile: 17.25
50th Percentile (Median): 23.0
75th Percentile: 31.25


##Q9. Broadcasting in NumPy  
Consider:
A = np.array([ \
[10, 20, 30], \
[40, 50, 60], \
[70, 80, 90] \
]) \
B = np.array([1, 2, 3]) \
Using NumPy broadcasting: \
• Task 1: Add B to every row of A. \
• Task 2: Multiply every row of A by B.\
• Task 3: Subtract B from every row of A. \
• Task 4: Divide every row of A by B. \
Finally, explain: \
• What is the shape of A?  
• What is the shape of B? \
• Why does broadcasting work here? \
• What would happen if B had shape (2,) instead?


In [10]:
a = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])
b=np.array([1, 2, 3])
t1=a+b
t2=a*b
t3=a-b
t4=a/b
print("add b to a :\n",t1)
print("multiply a by b :\n",t2)
print("subtract b from a :\n",t3)
print("divide a by b :\n",t4)
print("shape of a:",a.shape)
print("shape of b:",b.shape)
print("ans 3:Broadcasting works because the trailing dimensions are compatible")
print("ans 4:If B had a shape of (2,), the operations would crash and throw a ValueError")


add b to a :
 [[11 22 33]
 [41 52 63]
 [71 82 93]]
multiply a by b :
 [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
subtract b from a :
 [[ 9 18 27]
 [39 48 57]
 [69 78 87]]
divide a by b :
 [[10. 10. 10.]
 [40. 25. 20.]
 [70. 40. 30.]]
shape of a: (3, 3)
shape of b: (3,)
ans 3:Broadcasting works because the trailing dimensions are compatible
ans 4:If B had a shape of (2,), the operations would crash and throw a ValueError


## Q10. Vectorized Grade Assignment  

In [12]:
marks = np.array([35, 78, 92, 41, 56, 29, 88, 67])

conditions = [
    (marks >= 90) & (marks <= 100),
    (marks >= 80) & (marks <= 89),
    (marks >= 70) & (marks <= 79),
    (marks >= 50) & (marks <= 69),
    (marks >= 35) & (marks <= 49),
    (marks < 35)
]

choices = ['A+', 'A', 'B', 'C', 'D', 'F']

grades = np.select(conditions, choices, default='')

print("Student Grades:")
for mark, grade in zip(marks, grades):
    print(f"Mark: {mark} -> Grade: {grade}")
unique_grades, counts = np.unique(grades, return_counts=True)
grade_counts = dict(zip(unique_grades, counts))

print("\nGrade Category Counts:")
for grade in choices:
    print(f"Grade {grade}: {grade_counts.get(grade, 0)} student(s)")

Student Grades:
Mark: 35 -> Grade: D
Mark: 78 -> Grade: B
Mark: 92 -> Grade: A+
Mark: 41 -> Grade: D
Mark: 56 -> Grade: C
Mark: 29 -> Grade: F
Mark: 88 -> Grade: A
Mark: 67 -> Grade: C

Grade Category Counts:
Grade A+: 1 student(s)
Grade A: 1 student(s)
Grade B: 1 student(s)
Grade C: 2 student(s)
Grade D: 2 student(s)
Grade F: 1 student(s)
